// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RevenueModule.Api.Data;

#nullable disable

namespace RevenueModule.Api.Data.Migrations
{
    [DbContext(typeof(RevenueDbContext))]
    [Migration("20260505053504_Step1SeedAsciiNames")]
    partial class Step1SeedAsciiNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RevenueModule.Api.Models.Buyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("VipPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Buyers", t =>
                        {
                            t.HasCheckConstraint("CK_Buyers_VipPoint_NonNegative", "\"VipPoint\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buyer A",
                            VipPoint = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "Buyer B",
                            VipPoint = 7
                        },
                        new
                        {
                            Id = 3,
                            Name = "Buyer C",
                            VipPoint = 12
                        });
                });

            modelBuilder.Entity("RevenueModule.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("UnitPriceVnd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Products_UnitPriceVnd_NonNegative", "\"UnitPriceVnd\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "So tay mini",
                            UnitPriceVnd = 45000L
                        },
                        new
                        {
                            Id = 2,
                            Name = "Binh giu nhiet",
                            UnitPriceVnd = 320000L
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tai nghe co day",
                            UnitPriceVnd = 290000L
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ghe cong thai hoc",
                            UnitPriceVnd = 2150000L
                        },
                        new
                        {
                            Id = 5,
                            Name = "Man hinh 27 inch",
                            UnitPriceVnd = 4790000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
