// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RevenueModule.Api.Data;

#nullable disable

namespace RevenueModule.Api.Data.Migrations
{
    [DbContext(typeof(RevenueDbContext))]
    [Migration("20260505062115_Step3BillEntities")]
    partial class Step3BillEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RevenueModule.Api.Models.Bill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BaseBeforeVip")
                        .HasColumnType("bigint");

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Payable")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PendingAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("Subtotal")
                        .HasColumnType("bigint");

                    b.Property<long>("VipDiscountVnd")
                        .HasColumnType("bigint");

                    b.Property<long>("VipPointEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("VipPointUsed")
                        .HasColumnType("integer");

                    b.Property<long>("VoucherThuongAmount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.ToTable("Bills", t =>
                        {
                            t.HasCheckConstraint("CK_Bills_Payable_NonNegative", "\"Payable\" >= 0");
                        });
                });

            modelBuilder.Entity("RevenueModule.Api.Models.BillLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BillId")
                        .HasColumnType("bigint");

                    b.Property<long>("LineTotalVnd")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<long>("UnitPriceVnd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillLines", t =>
                        {
                            t.HasCheckConstraint("CK_BillLines_Qty_Positive", "\"Qty\" > 0");

                            t.HasCheckConstraint("CK_BillLines_UnitPrice_NonNegative", "\"UnitPriceVnd\" >= 0");
                        });
                });

            modelBuilder.Entity("RevenueModule.Api.Models.Buyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("VipPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Buyers", t =>
                        {
                            t.HasCheckConstraint("CK_Buyers_VipPoint_NonNegative", "\"VipPoint\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buyer A",
                            VipPoint = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "Buyer B",
                            VipPoint = 7
                        },
                        new
                        {
                            Id = 3,
                            Name = "Buyer C",
                            VipPoint = 12
                        });
                });

            modelBuilder.Entity("RevenueModule.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("UnitPriceVnd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Products_UnitPriceVnd_NonNegative", "\"UnitPriceVnd\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "So tay mini",
                            UnitPriceVnd = 45000L
                        },
                        new
                        {
                            Id = 2,
                            Name = "Binh giu nhiet",
                            UnitPriceVnd = 320000L
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tai nghe co day",
                            UnitPriceVnd = 290000L
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ghe cong thai hoc",
                            UnitPriceVnd = 2150000L
                        },
                        new
                        {
                            Id = 5,
                            Name = "Man hinh 27 inch",
                            UnitPriceVnd = 4790000L
                        });
                });

            modelBuilder.Entity("RevenueModule.Api.Models.Bill", b =>
                {
                    b.HasOne("RevenueModule.Api.Models.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("RevenueModule.Api.Models.BillLine", b =>
                {
                    b.HasOne("RevenueModule.Api.Models.Bill", "Bill")
                        .WithMany("Lines")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("RevenueModule.Api.Models.Bill", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
